# Generated by Django 5.0.7 on 2024-08-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Admission', '0004_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldata1',
            name='payment_ss',
            field=models.FileField(default='NA', upload_to='payment/'),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='trans_id',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='payment_ss',
            field=models.FileField(default='NA', upload_to='payment/'),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='trans_id',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='payment_ss',
            field=models.FileField(default='NA', upload_to='payment/'),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='trans_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
