# Generated by Django 3.2.25 on 2024-08-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Admission', '0007_alter_hosteldata1_fno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosteldata2',
            name='fno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hosteldata3',
            name='fno',
            field=models.CharField(max_length=255),
        ),
    ]
