# Generated by Django 3.2.25 on 2024-08-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Admission', '0008_auto_20240810_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosteldata1',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hosteldata2',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hosteldata3',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
