# Generated by Django 3.2.25 on 2024-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Admission', '0012_auto_20240811_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldata1',
            name='Year',
            field=models.CharField(default='First', max_length=7),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='Year',
            field=models.CharField(default='Second', max_length=7),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='Year',
            field=models.CharField(default='Third', max_length=7),
        ),
    ]
