# Generated by Django 5.0.7 on 2024-08-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Admission', '0013_auto_20240811_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldata1',
            name='pmerit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='pmerit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='pmerit',
            field=models.IntegerField(default=0),
        ),
    ]
